---
# tasks file for eclipse
# get binary
# untar it to /opt/
- name: Download and untar eclipse
  unarchive:
    src: "http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/R/eclipse-java-oxygen-R-linux-gtk-x86_64.tar.gz"
    dest: /opt/
    remote_src: true
    creates: "/opt/eclipse"

# symlink the binary to /usr/local/bin/eclipse

# ensure we have java
- name: Get java packages
  packages:
    package: jdk8-openjk
    state: latest

# get eclimd jar
# run headless install
