---
# tasks file for archlinux
- name: Add archlinux.fr to pacman.conf
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [archlinuxfr]
      SigLevel = Never
      Server = http://repo.archlinux.fr/$arch| 
  become: True
  tags: arch

- name: Update pacman
  shell: pacman -Syu
  become: True
  tags: arch

- name: install hasklig
  shell: yaourt hasklig
  tags: arch

- name: Arch specific packages
  package:
    name: {{ item }}
    state: latest
    with_items:
      - eclipse
  tags: arch
