#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -cursor_name left_ptr
xrdb ~/.Xresources
picom &
mpd &
~/.fehbg &

pgrep -x shkd > /dev/null || sxhkd &

# cases for nvidia card and hybrid
if xrandr -q | grep "HDMI-0 connected"; then
  # nvidia card + external HDMI
    bspc monitor HDMI-0 -d term dev web code spotify
    bspc monitor eDP-1-1 -d social
  else
  # no external
    bspc monitor eDP -d term dev web code spotify
fi

bspc config border_width	0
bspc config window_gap		12
bspc config top_padding		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc config pointer_mod mod1
bspc config pointer_action1 move

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc rule -a Gnome-calendar state=floating
bspc rule -a urxvt state=floating
bspc rule -a Alacritty desktop='^1'

# polybar goes last
~/.config/polybar/launch.sh &
