---
# tasks file for emacs
- name: Install latest version of emacs
  package:
    name: emacs
    state: latest
  become: true

# TODO: check for spacemacs install
# install spacemacs
- stat: "path={{ ansible_env.HOME }}/.spacemacs"
  register: dotspacemacs

- block:   
  - git:
      repo: "https://github.com/syl20bnr/spacemacs"
      dest: "{{ ansible_env.HOME }}/.emacs.d"
      update: yes
            
  - file:
      path: "{{ ansible_env.HOME }}/.spacemacs"
      state: absent

  - name: Symlink .spacemacs
    file:
      src: "{{ ansible_env.HOME}}/dotfiles/.spacemacs"
      dest: "{{ ansible_env.HOME }}/.spacemacs"
      state: link

  when: dotspacemacs.stat.exists == false

# install Hasklig
- name: Download and unzip Hasklig
  unarchive:
    src: "https://github.com/i-tu/Hasklig/releases/download/{{ hasklig_version }}/Hasklig-{{ hasklig_version }}.zip"
    dest: /usr/share/fonts
    remote_src: true
    creates: "/usr/share/fonts/Hasklig-{{ hasklig_version }}.zip"
  become: true
  vars: 
    hasklig_version: "1.1"
# when the zip file doesn't exist

- name: Update font cache
  command: fc-cache
      

