---
# install node with nvm
- name: Install nvm
  package:
    name: nvm
    state: latest
  become: true

- stat: path="{{ ansible_env.HOME }}/.nvm"
  register: nvm_directory
  
- block:
  - get_url:
      url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
      dest: "{{ nvm }}" 
  - script: "{{ nvm }}"
  vars:
    nvm_version: "0.32.1"
    nvm: "{{ ansible_env.HOME }}/dotfiles/nvm_{{ nvm_version }}.sh"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm"


# sh -c "$(curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh)"
# export NVM_DIR="~/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# nvm install node
# nvm use node

- name: Install node with nvm
  shell: "nvm install node && nvm use node"
