---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
  tags: node

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ nvm_dependencies }}"
  become: True
  tags: nvm

- name: Install nvm
  git: "repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }}"

- name: Source nvm in ~/.profile
  become: True
  become_user: "{{ local.user }}"
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
    create=yes
  tags: nvm

- name: "Install {{ nvm.node_version }}"
  command: "nvm install {{ nvm.node_version }}"
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stdout"
  become: True
  become_user: "{{ local.user }}"
  tags: nvm

- name: "Check if {{ nvm.node_version }} is the default node version"
  shell: "nvm ls | grep -e 'default -> {{ nvm.node_version }}'"
  register: nvm_check_default
  changed_when: False
  ignore_errors: True
  become: True
  become_user: "{{ local.user }}"
  tags: nvm

- name: "Set default node version to {{ nvm.node_version }}"
  command: "nvm alias default {{ nvm.node_version }}"
  when: nvm_check_default|failed
  become: True
  become_user: "{{ local.user }}"
  tags: nvm
